type: prometheus

status:
  class: receiver
  stability:
    beta: [metrics]
  distributions:
  - core
  - contrib
  - aws
  - grafana
  - observiq
  - splunk
  - sumo
  - liatrio
  codeowners:
    active: [Aneurysm9, dashpole]
